config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  get "pricing", to: "static_pages#pricing"
  root "posts#index"
  resources :posts
  post "checkout/create", to: "checkout#create", as: "checkout_create"
  post "billing_portal/create", to: "billing_portal#create", as: "billing_portal_create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, :content, presence: true


    scope :free, -> { where(premium: false)} 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  def create_stripe_id
    response = Stripe::Customer.list({email: email})
    update(stripe_customer_id: response[:data].first.id)
  end

  after_create do
    customer = Stripe::Customer.create(email: email)
    update(stripe_customer_id: customer.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/billing_portal_controller.rb
class BillingPortalController < ApplicationController

    def create  
      portal_session = Stripe::BillingPortal::Session.create({
        customer: current_user.stripe_customer_id,
        return_url: root_url,
      })
      redirect_to portal_session.url
    end
  
  end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  
    def create
      @session = Stripe::Checkout::Session.create({
        customer: current_user.stripe_customer_id,
        success_url: posts_url,
        cancel_url: pricing_url,
        payment_method_types: ['card'],
        line_items: [
          {price: params[:price], quantity: 1},
        ],
        mode: 'subscription',
      })
      respond_to do |format|
        format.js
      end
    end
    
  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    if current_user.subscription_status == 'active'
      @posts = Post.all
    else
      @posts = Post.free
    end
  end

  # GET /posts/1 or /posts/1.json
  def show
    if @post.premium? && current_user.subscription_status != 'active'
      redirect_to posts_path, alert: "Only for active subscriptions"
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content, :premium)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def pricing
  end
end  

app/controllers/webhooks_controller.rb
class WebhooksController < ApplicationController
    skip_before_action :authenticate_user!
    skip_before_action :verify_authenticity_token
  
    def create
      payload = request.body.read
      sig_header = request.env['HTTP_STRIPE_SIGNATURE']
      event = nil
  
      begin
        event = Stripe::Webhook.construct_event(
          payload, sig_header, Rails.application.credentials.dig(:stripe, :webhook)
        )
      rescue JSON::ParserError => e
        status 400
        return
      rescue Stripe::SignatureVerificationError => e
        # Invalid signature
        puts "Signature error"
        p e
        return
      end
  
      # Handle the event
      case event.type
      when 'checkout.session.completed'
        session = event.data.object
        @user = User.find_by(stripe_customer_id: session.customer)
        @user.update(subscription_status: 'active')
      when 'customer.subscription.updated', 'customer.subscription.deleted'
        subscription = event.data.object
        @user = User.find_by(stripe_customer_id: subscription.customer)
        @user.update(
          subscription_status: subscription.status,
          plan: subscription.items.data[0].price.lookup_key,
        )
      end
  
      render json: { message: 'success' }
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/checkout/create.js.erb
var stripe = Stripe('pk_test_51MWmjkHFC97yK2BpZE31VXli8N7HNcqOgaPGfPpLlzKfTnZHDtOjXFmhY2eUiHRMorGSNiwjMOKygRlHbtFirUK500hdkPaaJW');

stripe.redirectToCheckout({
  sessionId: '<%= @session.id %>'
}).then( function(result){
  console.log('oiee')

});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SaasBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://js.stripe.com/v3/"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <br>
    <%= link_to  "Post", posts_path%>
    <%= link_to "Pricing", pricing_path %>
   
    <% if current_user %>
     <%= current_user.subscription_status%>
     <p>Id USer: <%= "#{current_user.stripe_customer_id}" %></p>
      <%= link_to "Checkout", checkout_create_path, method: :post, remote: true %>
      <%= link_to "BillingPortal", billing_portal_create_path, method: :post %>
      <%= link_to current_user.email, edit_user_registration_path %>
      <%= link_to "Log out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Log in", new_user_session_path %>
      <%= link_to "Register", new_user_registration_path %>
    <% end %>
    <hr>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :premium, style: "display: block" %>
    <%= form.check_box :premium %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>

<%= link_to "New post", new_post_path %>
<div id="posts">
 <table>
  <thead>
    <tr>
      <th>title</th>
      <th>content</th>
      <th>premium</th>
      <th>Stripe Product ID:</th>
      <th>Stripe Price ID:</th>
    </tr>
  </thead>
  
  <tbody>
    <% @posts.each do |post| %>
      <td><%= truncate(post.title, length: 5) %></td>
      <td><%= truncate(post.content, length: 5) %></td>
      <td>
        <%= link_to "Show this post", post %>
      </td>
    <% end %>
  </tbody>
 </table>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>


<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

app/views/static_pages/pricing.html.erb
<h1>Pricing</h1>

<% @pricing = Stripe::Price.list(lookup_keys: ["good_year", "good_month"], expand: ["data.product"]) %>
<% @pricing.each do |price| %>
  <br>
  <%= price.product.name %>
  <%= price.id %>
  <%= price.unit_amount/100 %>
  <%= price.currency %>
  <%= price.recurring.interval %>
  <%= link_to "Checkout", checkout_create_path(price: price.id), method: :post, remote: true %>

<% end %>